apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-myprojectfinaktiva
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: finaktiva
        image: finaktiva/myprojectfinaktiva:V1
        